-- Incluir los insert para cargar la BBDD.
INSERT INTO ESQUEMA.PERSON (AGE, NAME) VALUES(18, 'Charles');
INSERT INTO ESQUEMA.PERSON (AGE, NAME) VALUES(28, 'Felipe');
INSERT INTO ESQUEMA.PERSON (AGE, NAME) VALUES(15, 'Jenny');
INSERT INTO ESQUEMA.PERSON (AGE, NAME) VALUES(99, 'Potato');
INSERT INTO ESQUEMA.PERSON (AGE, NAME) VALUES(30, 'Nicolas');
